name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: run unit tests
      run: go test -v ./...
